site:
  title: Quick Course Experiments with Claude Code
  start_page: quickcourse-claude-test::index.adoc

content:
  sources:
  - url: ./
    branches: HEAD
  - url: ../quickcourse-claude-test-samples
    branches: HEAD

asciidoc:
  attributes:
    page-pagination: true
    experimental: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
