site:
  title: Quick Course Experiments with Claude Code
  start_page: quickcourse-claude-test::index.adoc

content:
  sources:
  - url: ./
    branches: HEAD
  - url: https://github.com/flozanorht/quickcourse-claude-test-samples.git
    branches: main

asciidoc:
  attributes:
    page-pagination: true
    experimental: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
